//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EddiSerialResponder.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SerialResponder {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SerialResponder() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EddiSerialResponder.Properties.SerialResponder", typeof(SerialResponder).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active cockpit.
        /// </summary>
        public static string active_cockpit {
            get {
                return ResourceManager.GetString("active_cockpit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy cockpit.
        /// </summary>
        public static string button_copy {
            get {
                return ResourceManager.GetString("button_copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete cockpit.
        /// </summary>
        public static string button_delete {
            get {
                return ResourceManager.GetString("button_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new sctipt.
        /// </summary>
        public static string button_new {
            get {
                return ResourceManager.GetString("button_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default cockpit cannot be modified. If you wish to make changes, create a copy..
        /// </summary>
        public static string default_is_read_only {
            get {
                return ResourceManager.GetString("default_is_read_only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respond to events by sending user-scripted data over a serial port. Use this responder to build your own physical cockpit panels.
        /// </summary>
        public static string desc {
            get {
                return ResourceManager.GetString("desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string header_description {
            get {
                return ResourceManager.GetString("header_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string header_enabled {
            get {
                return ResourceManager.GetString("header_enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string header_name {
            get {
                return ResourceManager.GetString("header_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string help_button {
            get {
                return ResourceManager.GetString("help_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write logs of the serial commands to the file %APPDATA%\EDDI\serialresponder.out.
        /// </summary>
        public static string logs {
            get {
                return ResourceManager.GetString("logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not send data over the serial port when logs are enabled.
        /// </summary>
        public static string logs_only {
            get {
                return ResourceManager.GetString("logs_only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Responder.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read about the serial responder&apos;s functions.
        /// </summary>
        public static string serialResponderHelp {
            get {
                return ResourceManager.GetString("serialResponderHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here..
        /// </summary>
        public static string serialResponderHelpHere {
            get {
                return ResourceManager.GetString("serialResponderHelpHere", resourceCulture);
            }
        }
    }
}
